### ISSUE TITLE
Vertebrate Trait data-version

### ISSUE THREAD

**Issue by ima23** [AnimalGenome/vertebrate-trait-ontology#1]
Hello,
thanks for providing the Vertebrate Trait ontology files! Would it be possible to include a `data-version` field in the OBO header? For example `data-version: releases/2018-01-26` or  `data-version: 2018-01-26`. This would help the automatic import scripts applied on the ontology maintain the version and be consistent with other OBO ontologies out there.
Thanks,
Irina

**Comment by caripark** [comment]
Thank you for the suggestion! I've added the header to the latest ontology file.
