### ISSUE TITLE
Clean old/duplciate  versions fo VT in AgroPortal

### ISSUE THREAD

**Issue by jonquet** [AnimalGenome/vertebrate-trait-ontology#11]
Hello @zhilianghu @zhiliangme 
Can you ou tell us if its ok to clean some duplicate of 11.4 in AgroPortal ? 

<img width="606" alt="Capture d’écran 2024-06-06 à 14 49 43" src="https://github.com/AnimalGenome/vertebrate-trait-ontology/assets/7379183/650bc557-207f-4abc-af94-41e6f3c25df6">

Idem for 12.1

If you want us to do it, please confirm whcih one we shall keep (the last? )

Related to https://github.com/agroportal/project-management/issues/140

**Comment by caripark** [comment]
Yes, it is fine to get rid of the duplicates. Please retain the first one, from February 17, 2021. Thank you!

**Comment by jonquet** [comment]
ok I will do it with a script soon

**Comment by jonquet** [comment]
Closing as done in AgroPortal. I have also kept only one version per month since 2024
