### ISSUE TITLE
root definition and name

### ISSUE THREAD

**Issue by sbello** [AnimalGenome/vertebrate-trait-ontology#2]
Hi Cari,
I just noticed that we made the root term 'trait' and defined it as 'Any measurable or observable characteristic of an organism.' This strikes me as overly broad since we only intended to cover vertebrates. We may want to change this to 'vertebrate trait' and make the definition 'Any measurable or observable characteristic of a vertebrate organism.' to better reflect the scope of the ontology.
Thanks,
Sue

**Comment by caripark** [comment]
Thanks, Sue--I've made the change.
