### ISSUE TITLE
Correct syntax error on version metadata property. 

### ISSUE THREAD

**Issue by jonquet** [AnimalGenome/vertebrate-trait-ontology#9]
Current release vt.owl file contains: 

<oboInOwl:Data-version>13.14</oboInOwl:Data-version>

This must be corrected to <oboInOwl:data-version>13.14</oboInOwl:data-version>
as this is a property. 

Seems the problem comes directly from the .obo file which contains: 
`Data-version:13.14` 

Ideally, to be more standard I would recommend to switch to owl:versionInfo

**Comment by caripark** [comment]
The switch has been made to owl:versioninfo.
